namespace Obsidian.API.Inventory.DataComponents;

public static partial class ComponentBuilder
{
    // Key by generated registry enum, never by position in a hand-maintained array.
    public static DataComponent? Create(DataComponentType type) => type switch
    {
        DataComponentType.MaxStackSize => MaxStackSize,
        DataComponentType.MaxDamage => MaxDamage,
        DataComponentType.Damage => Damage,
        DataComponentType.Unbreakable => Unbreakable,
        DataComponentType.CustomName => CustomName,
        DataComponentType.ItemName => ItemName,
        DataComponentType.ItemModel => ItemModel,
        DataComponentType.Lore => Lore,
        DataComponentType.Rarity => Rarity,
        DataComponentType.Enchantments => Enchantments,
        DataComponentType.RepairCost => RepairCost,
        DataComponentType.CreativeSlotLock => CreativeSlotLock,
        DataComponentType.EnchantmentGlintOverride => EnchantmentGlintOverride,
        DataComponentType.Food => new FoodDataComponent(),
        DataComponentType.UseRemainder => UseRemainder,
        DataComponentType.UseCooldown => new UseCooldownDataComponent(),
        DataComponentType.Tool => new ToolDataComponent(),
        DataComponentType.Enchantable => Enchantable,
        DataComponentType.Glider => Glider,
        DataComponentType.TooltipStyle => TooltipStyle,
        DataComponentType.StoredEnchantments => StoredEnchantments,
        DataComponentType.DyedColor => DyedColor,
        DataComponentType.MapColor => MapColor,
        DataComponentType.MapId => MapId,
        DataComponentType.MapPostProcessing => MapPostProcessing,
        DataComponentType.ChargedProjectiles => ChargedProjectiles,
        DataComponentType.BundleContents => BundleContents,
        DataComponentType.PotionContents => new PotionContentsDataComponent(),
        DataComponentType.SuspiciousStewEffects => SuspiciousStewEffects,
        DataComponentType.WritableBookContent => WritableBookContent,
        DataComponentType.Instrument => Instrument,
        DataComponentType.OminousBottleAmplifier => OminousBottleAmplifier,
        DataComponentType.LodestoneTracker => new LodestoneTrackerDataComponent(),
        DataComponentType.FireworkExplosion => FireworkExplosion,
        DataComponentType.Fireworks => new FireworksDataComponent(),
        DataComponentType.NoteBlockSound => NoteBlockSound,
        DataComponentType.BaseColor => BaseColor,
        DataComponentType.PotDecorations => PotDecorations,
        DataComponentType.Container => Container,
        DataComponentType.BlockState => BlockState,
        DataComponentType.Consumable => new ConsumableDataComponent(),
        DataComponentType.Equippable => new EquippableDataComponent(),
        DataComponentType.Profile => new ProfileDataComponent(),
        DataComponentType.Trim => new TrimDataComponent(),
        DataComponentType.MapDecorations => new MapDecorationDataComponent(),
        DataComponentType.CustomModelData => new CustomModelDataComponent(),
        DataComponentType.WrittenBookContent => new WrittenBookDataComponent(),
        DataComponentType.DeathProtection => DeathProtection,
        DataComponentType.Repairable => Repairable,
        DataComponentType.DamageResistant => DamageResistant,
        DataComponentType.AttributeModifiers => AttributeModifiers,
        DataComponentType.BannerPatterns => BannerPatterns,
        DataComponentType.JukeboxPlayable => new JukeboxPlayableDataComponent(),
        DataComponentType.CustomData => CustomData,
        DataComponentType.IntangibleProjectile => IntangibleProjectile,
        DataComponentType.DebugStickState => DebugStickState,
        DataComponentType.BucketEntityData => BucketEntityData,
        DataComponentType.Lock => Lock,
        DataComponentType.ContainerLoot => ContainerLoot,
        DataComponentType.CanPlaceOn => new CanPlaceOnDataComponent(),
        DataComponentType.CanBreak => new CanBreakDataComponent(),
        DataComponentType.EntityData => EntityData,
        DataComponentType.BlockEntityData => BlockEntityData,
        DataComponentType.Bees => Bees,
        DataComponentType.Recipes => Recipes,
        _ => null
    };
}
