version: "3.9" # Docker compose version, NOT project version

services:
  obsidian:
    build: .
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - obsidian-files:/files

volumes:
    obsidian-files:
        {}