namespace Obsidian.Entities
{
    public enum EntityType : byte
    {
        AreaEffectCloud,
        ArmorStand,
        Arrow,
        Bat,
        Blaze,
        Boat,
        CaveSpider,
        Chicken,
        Cod,
        Cow,
        Creeper,
        Donkey,
        Dolphin,
        DragonFireball3,
        Drowned,
        ElderGuardian,
        EnderCrystal,
        EnderDragon,
        Enderman,
        Endermite,
        EvocationFangs,
        EvocationIllager,
        XPOrb,
        EnderSignal,
        FallingSand,
        Firework,
        Ghast,
        Giant,
        Guardian,
        Horse,
        Husk,
        IllusionIllager,
        Item,
        ItemFrame,
        /// <summary>
        /// Ghast Fireball
        /// </summary>
        Fireball,
        Leash,
        Llama,
        LlamaSpit,
        /// <summary>
        /// Lava Slime
        /// </summary>
        MagmaCube,
        Minecart,
        MinecartChest,
        MinecartCommandBlock,
        MinecartFurnace,
        MinecartHopper,
        MinecartSpawner,
        MinecartTnt,
        Mule,
        /// <summary>
        /// The Mooshroom
        /// </summary>
        MushroomCow,
        Ocelot,
        Painting,
        Parrot,
        Pig,
        Pufferfish,
        PigZombie,
        PolarBear,
        PrimedTnt,
        Rabbit,
        Salmon,
        Sheep,
        Shulker,
        ShulkerBullet,
        Silverfish,
        Skeleton,
        SkeletonHorse,
        Slime,
        /// <summary>
        /// Blaze fireball.
        /// </summary>
        SmallFireball,
        SnowMan,
        Snowball,
        SpectralArrow,
        Spider,
        Squid,
        Stray,
        TropicalFish,
        Turtle,
        Egg,
        Enderpearl,
        ExpBottle,
        SplashPotion,
        Vex,
        Villager,
        IronGolem,
        VindicatorIllager,
        Witch,
        Wither,
        WitherSkeleton,
        WitherSkull,
        Wolf,
        Zombie,
        ZombieHorse,
        ZombieVillager,
        Lightning,
        Player,
        FishingBobber,
        Trident
    }
}
