namespace Obsidian.API;
public enum EntityMetadataType : int
{
    Byte = 0,
    VarInt = 1,
    VarLong = 2,
    Float = 3,
    String = 4,
    TextComponent = 5,
    OptionalTextComponent = 6,
    Slot = 7,
    Boolean = 8,
    Rotations = 9,
    BlockPos = 10,
    OptionalBlockPos = 11,
    Direction = 12,
    OptionalLivingEntityReference = 13,
    BlockState = 14,
    OptionalBlockState = 15,
    CompoundTag = 16,
    Particle = 17,
    Particles = 18,
    VillagerData = 19,
    OptionalUnsignedVarInt = 20,
    Pose = 21,
    CatVariant = 22,
    CowVariant = 23,
    WolfVariant = 24,
    WolfSoundVariant = 25,
    FrogVariant = 26,
    PigVariant = 27,
    ChickenVariant = 28,
    OptionalGlobalPos = 29,
    PaintingVariant = 30,
    SnifferState = 31,
    ArmadilloState = 32,
    Vector3 = 33,
    Quaternion = 34
}
