namespace Obsidian.API;
public enum EntityMetadataType : int
{
    Byte = 0,
    VarInt = 1,
    VarLong = 2,
    Float = 3,
    String = 4,
    TextComponent = 5,
    OptionalTextComponent = 6,
    Slot = 7,
    Boolean = 8,
    Rotations = 9,
    BlockPos = 10,
    OptionalBlockPos = 11,
    Direction = 12,
    OptionalLivingEntityReference = 13,
    BlockState = 14,
    OptionalBlockState = 15,
    Particle = 16,
    Particles = 17,
    VillagerData = 18,
    OptionalUnsignedVarInt = 19,
    Pose = 20,
    CatVariant = 21,
    CowVariant = 22,
    WolfVariant = 23,
    WolfSoundVariant = 24,
    FrogVariant = 25,
    PigVariant = 26,
    ChickenVariant = 27,
    OptionalGlobalPos = 28,
    PaintingVariant = 29,
    SnifferState = 30,
    ArmadilloState = 31,
    Vector3 = 32,
    Quaternion = 33,
    ResolvableProfile = 34
}
