using Obsidian.API.Inventory;
using Obsidian.API.Inventory.DataComponents;
using Obsidian.API.Loot;
using Obsidian.WorldData.Generators;
using Obsidian.WorldData.Generators.Mojang.Structures;

namespace Obsidian.WorldData.Maps;

/// <summary>
/// Creates explorer maps for a level generated by <see cref="MojangGenerator"/>, like vanilla's <c>ExplorationMapFunction</c>.
/// </summary>
internal sealed class ExplorationMaps(AbstractLevel level, MojangGenerator generator) : IExplorationMapFactory
{
    // Decoration types with a map item color (vanilla's MapDecorationType.mapColor).
    private static readonly Dictionary<MapDecorationType, int> decorationColors = new()
    {
        { MapDecorationType.Mansion, 5393476 },
        { MapDecorationType.Monument, 3830373 },
        { MapDecorationType.TrialChambers, 12741452 }
    };

    /// <summary>
    /// The explorer map factory of a level, or <c>null</c> when its generator doesn't place vanilla structures.
    /// </summary>
    public static ExplorationMaps? For(ILevel level) =>
        level is AbstractLevel generated && generated.Generator is MojangGenerator mojang ? new ExplorationMaps(generated, mojang) : null;

    public ItemStack? Create(ExplorationMapRequest request)
    {
        var structures = generator.Builder.Structures;
        var tag = request.Destination.StartsWith('#') ? request.Destination[1..] : request.Destination;
        if (structures is null || !StructureTags.All.TryGetValue(tag, out var targets))
            return null;

        var origin = new Vector((int)Math.Floor(request.Origin.X), (int)Math.Floor(request.Origin.Y), (int)Math.Floor(request.Origin.Z));
        var found = new StructureLocator(structures).FindNearest(targets, origin, request.SearchRadius, request.SkipKnownStructures);
        if (found is null)
            return null;

        var position = found.Value;
        var storage = MapStorage.For(level);
        var map = storage.CreateMap(position.X, position.Z, (byte)request.Zoom, trackingPosition: true, unlimitedTracking: true, level.DimensionName);
        var data = storage.Get(MapStorage.GetMapId(map)!.Value)!;
        MapRenderer.RenderBiomePreview(data, (x, z) => generator.Builder.GetBiome(x, 0, z));

        // Vanilla addTargetDecoration: the target is stored on the item, and drawn once the map is carried.
        var type = Enum.Parse<MapDecorationType>(request.Decoration.Replace("minecraft:", string.Empty).ToPascalCase(), true);
        map[DataComponentType.MapDecorations] = new MapDecorationDataComponent
        {
            Decorations = new() { ["+"] = new MapDecoration { Type = type, X = position.X, Z = position.Z, Rotation = 180.0f } }
        };

        if (decorationColors.TryGetValue(type, out var color))
            map[DataComponentType.MapColor] = ComponentBuilder.MapColor with { Value = color };

        return map;
    }
}
